Repository Lakhankumawat/LearnCPP, pull requests merged in 2022-03, with the labels that each got.

#251 Delete A node in linked list CPP #94
  L-LinkedList/Delete a node in LinkedList/delete_node_ll.cpp
  L-LinkedList/Delete a node in LinkedList/delete_node_ll.md
Labels: enhancement, Approved, Feature-addition, problem-statement-addition, Level1, GSSoC22

#369 #330: Created a C++ file and updated readme for Equal sum partition
  D-DynamicProgramming/Equal_Sum_Partition.cpp
  D-DynamicProgramming/README.md
Labels: enhancement, Feature-addition, problem-statement-addition, admin

#81 Added Kadane's Algorithm and Readme in D-Dynamic Programming Folder
  D-DynamicProgramming/Kadane's Algorithm/Kadane's Algorithm.cpp
  D-DynamicProgramming/Kadane's Algorithm/README.md
Labels: enhancement, Feature-addition, GSSoC22, algorithm, admin

#446 Update README.md
  README.md
Labels: enhancement, Approved, Feature-addition

#50 Added counting sort algorithm
  S-SortingAlgorithms/CountingSort.cpp
  S-SortingAlgorithms/README.md
Labels: enhancement, Feature-addition, next review needed, assigned, g2m, admin

#402 Primediv
  M-MathematicalAlgorithms/README.md
  M-MathematicalAlgorithms/primeSum.cpp
Labels: enhancement, Feature-addition, problem-statement-addition, g1g

#196 Insert node at nth position in the linked list
  L-LinkedList/Insert_new_node_at_nth_position.cpp
  L-LinkedList/README.md
Labels: enhancement, good first issue, Feature-addition, next review needed, GSSoC22, g2m, admin

#366 #195 (Infix to Postfix expression conversion(application of stack))
  S-Stack/InfixToPostfix.cpp
  S-Stack/README.md
Labels: enhancement, Feature-addition, problem-statement-addition, incomplete-checks, admin, changes-pending

#286 add new file Morris_Traversal in T-TreeTraversal
  T-Tree/T-TreeTraversals/Morris_Traversal.cpp
  T-Tree/T-TreeTraversals/README.md
Labels: enhancement, Feature-addition, next review needed, algorithm, admin, changes-pending

#513 Cartesian product
  S-Sets/Cartesian_Product.cpp
  S-Sets/README.md
Labels: enhancement, Feature-addition, problem-statement-addition, admin

#242 Map STL in HashMap
  H-HashMap/Map.cpp
  H-HashMap/README.md
Labels: enhancement, Feature-addition, STL, admin

#165 Sort an array of 0s, 1s and 2s
  A-Array/README.md
  A-Array/Sort_0_1_2.cpp
Labels: enhancement, Feature-addition, problem-statement-addition, Level1, g1g

#304 Reverse a Queue #269
  Q-Queue/README.md
  Q-Queue/ReverseQueue.cpp
Labels: enhancement, Feature-addition, problem-statement-addition, short-desc, g1g

#496 Added a code for Create, Display, Insert and delete a node in Singly Linked List
  L-LinkedList/SLL - Create, Display, Insert and Delete a node/1.SLL - Create,Display,Insert and Delete a node.cpp
  L-LinkedList/SLL - Create, Display, Insert and Delete a node/README.md
Labels: enhancement, Feature-addition, DataStructure, short-desc, g1g

#376 Avl tree
  T-Tree/B-BinarySearchTree/AVL.cpp
  T-Tree/B-BinarySearchTree/readme.md
Labels: enhancement, Feature-addition, DataStructure, g1g

#296 Prefix Sum in 1-D array#257
  P-PrefixSum1D/README.md
  P-PrefixSum1D/img.png
  P-PrefixSum1D/prefixsum1D.cpp
Labels: enhancement, Feature-addition, problem-statement-addition, g1g

#475 updated Paranthesis Matching
  S-Stack/Bracket Balancing Using Stack/Bracket_Balancing_using_Stack.cpp
  S-Stack/Bracket Balancing Using Stack/README.md
Labels: enhancement, Feature-addition, problem-statement-addition, GSSoC22, admin

#384 Subset
  D-DynamicProgramming/README.md
  D-DynamicProgramming/SubsetSum.cpp
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, GSSoC22, admin

#564 Generic tree creating and display
  T-Tree/G-GenricTree/README.md
  T-Tree/G-GenricTree/constructAndDisplayGenrictree.cpp
Labels: enhancement, Feature-addition, DataStructure, admin

#582 changed directory of the problem with updated README as mentioned
  D-DynamicProgramming/README.md
  D-DynamicProgramming/TrappingRainWater.cpp
Labels: enhancement, Feature-addition

#541 Find Normal and Trace of a matrix using array
  A-Array/README.md
  A-Array/TraceAndNormal.cpp
Labels: enhancement, Feature-addition, problem-statement-addition, admin

#516 Merge K sorted linked list Done
  L-LinkedList/Merge K Sorted LinkedList/README.md
  L-LinkedList/Merge K Sorted LinkedList/merge_k_ll.cpp
Labels: enhancement, Feature-addition, problem-statement-addition, admin

#605 # 604 Refactoring Vector Implementation
  S-STL/C-Containers/V-Vector/Vector_Operations.cpp
Labels: enhancement, Feature-addition, admin

#587 added k-largest elements in array
  H-Heap/README.md
  H-Heap/klargest.cpp
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, g2m, README, admin, changes-pending

#569 Segregate Even Odd Node Of LinkedList
  L-LinkedList/S-SinglyLinkedList/README.md
  L-LinkedList/S-SinglyLinkedList/SegregateEvenOdd.cpp
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, short-desc, g2m, README, admin, changes-pending

#566 Height of Binary Tree
  T-Tree/B-BinaryTree/Height_of_Tree.cpp
  T-Tree/B-BinaryTree/README.md
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, g2m, README, admin, changes-pending

#626 Update README.md
  S-SearchingAlgorithms/README.md
Labels: enhancement, Feature-addition, next review needed, admin, changes-pending

#655 Largest Binary Search Tree in a Binary Tree
  T-Tree/B-BinaryTree/LargestBSTinBT.cpp
  T-Tree/B-BinaryTree/README.md
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, admin, changes-pending

#659 Update README.md
  S-SearchingAlgorithms/README.md
Labels: enhancement, Feature-addition, next review needed, proposal, admin, changes-pending

#678 Update README.md
  S-SortingAlgorithms/README.md
Labels: enhancement, Feature-addition, next review needed, proposal, admin, changes-pending

#528 Maximum Sum of subarray
  A-Array/MaximumSumSubarray.cpp
  A-Array/README.md
Labels: enhancement, Feature-addition, admin

#490 Issue: #466 Created c++ and updated readme file for Minimum insertion to form a palindrome
  D-DynamicProgramming/Minimum_insertions_form_palindrome.cpp
  D-DynamicProgramming/README.md
Labels: enhancement, Feature-addition, problem-statement-addition, admin

#688 Diameter of a Generic Tree
  T-Tree/G-GenricTree/DiameterofGenricTree.cpp
  T-Tree/G-GenricTree/README.md
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, GSSoC22, README, admin, changes-pending

#272 Reverse a singly Linked List
  L-LinkedList/S-SinglyLinkedList/README.md
  L-LinkedList/S-SinglyLinkedList/README_Reverse_Linked_List.md
  L-LinkedList/S-SinglyLinkedList/ReverseLinkedList.cpp
Labels: enhancement, Approved, Feature-addition, next review needed, problem-statement-addition, README, admin

#494 Update README.md of Static implementation of Stack
  S-Stack/README.md
Labels: enhancement, Approved, Feature-addition, Level1, GSSoC22

#517 Bipartite Graph
  G-Graphs/B-BipartiteGraph/README.md
  G-Graphs/B-BipartiteGraph/checkBipartite.cpp
Labels: enhancement, Feature-addition, next review needed, DataStructure, README, admin, changes-pending

#275 added LongestCommonSubsequence.cpp in dynamic programming and updated…
  D-DynamicProgramming/LongestCommonSubsequence.cpp
  D-DynamicProgramming/README.md
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, g2n, admin

#314 created a c++ file and updated readme
  .vscode/settings.json
  O-OOPS/ConstructorDestructor.cpp
  O-OOPS/README.md
  O-OOPS/constructor_destructor.exe
Labels: enhancement, Feature-addition, next review needed, admin

#484 Diameter of The Binary-Tree
  T-Tree/B-BinaryTree/Diameter.cpp
  T-Tree/B-BinaryTrees/README.md
Labels: enhancement, Feature-addition, problem-statement-addition, admin

#690 Middle element of the linked list(two pointer approach)
  L-LinkedList/S-SinglyLinkedList/README.md
  L-LinkedList/S-SinglyLinkedList/middleElementOfLinkedList.cpp
Labels: enhancement, Feature-addition, problem-statement-addition, admin

#630 #629RedundantParenthesis
  S-Stack/RedundantParenthesis/README.md
  S-Stack/RedundantParenthesis/RedudantParenthesis.cpp
Labels: enhancement, Feature-addition, problem-statement-addition, admin

#661 Floor Value in Binary Search Tree(BST)
  T-Tree/B-BinarySearchTree/Floor Value in BST/FloorValueBST.cpp
  T-Tree/B-BinarySearchTree/Floor Value in BST/Readme.md
Labels: enhancement, Feature-addition, problem-statement-addition, admin

#482 Tower-of-Hanoi
  R-Recursion/README.md
  R-Recursion/Tower-of-Hanoi
Labels: enhancement, Feature-addition, problem-statement-addition, admin

#380 Update README.md of Recursion
  R-Recursion/README.md
Labels: enhancement, Feature-addition, g1s, admin

#729 Ceil Value in BST
  T-Tree/B-BinarySearchTree/Ceil Value in BST/CeilValue.cpp
  T-Tree/B-BinarySearchTree/Ceil Value in BST/readme.md
Labels: enhancement, Feature-addition, problem-statement-addition, README, admin, changes-pending, CGC

#310 Add Egg Dropping Problem to Dynamic Programming folder
  D-DynamicProgramming/EggDroppingPuzzle.cpp
  D-DynamicProgramming/README.md
Labels: enhancement, Feature-addition, problem-statement-addition, admin

#818 Algorithm Peak in 1D Array
  A-Array/Peak.cpp
  A-Array/README.md
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, incomplete-checks, README, admin

#864 Mirror of a Generic Tree
  T-Tree/G-GenricTree/MirrorOfGenricTree.cpp
  T-Tree/G-GenricTree/README.md
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, algorithm, admin, changes-pending

#483 Stock Buy And Sell
  A-Array/README.md
  A-Array/Stock Buy And Sell.cpp
Labels: enhancement, Feature-addition, problem-statement-addition, admin

#825 Sorted array to bst
  T-Tree/B-BinarySearchTree/Arraytobst.cpp
  T-Tree/B-BinarySearchTree/readme.md
Labels: enhancement, Feature-addition, problem-statement-addition, g1s, changes-pending
