Repository Lakhankumawat/LearnCPP, pull requests merged in 2022-05, with the labels that each got.

#1264 Removing duplicates from sorted singly linked list
  L-LinkedList/S-SinglyLinkedList/README.md
  L-LinkedList/S-SinglyLinkedList/RemovingDuplicates.cpp
Labels: enhancement, Feature-addition, next review needed, DataStructure, admin, changes-pending

#1175 DNF Sort Explanation added
  S-SortingAlgorithms/README.md
Labels: enhancement, Feature-addition, next review needed, algorithm, README, admin

#1277 Multiple inheritance
  O-OOPS/I-Inheritance/Multiple-Inheritance.cpp
  O-OOPS/I-Inheritance/README.md
Labels: enhancement, Feature-addition, next review needed, DataStructure, admin

#1295 Hierarchical inheritance
  O-OOPS/I-Inheritance/Hierarchical-Inheritance.cpp
  O-OOPS/I-Inheritance/README.md
Labels: enhancement, Feature-addition, next review needed, admin

#1286 Printing matrix in antispiral form
  A-Array/AntispiralMatrix.cpp
  A-Array/README.md
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, admin

#1290 Subset Sum
  B-Backtracking/README.md
  B-Backtracking/SubsetSum.cpp
Labels: enhancement, Feature-addition, next review needed, DataStructure, admin

#1276 Search element in rotated sorted array using binary search #635
  S-SearchingAlgorithms/README.md
  S-SearchingAlgorithms/SearchElementRotatedSortedArray.cpp
Labels: enhancement, Feature-addition, admin

#1304 Hybrid inheritance
  O-OOPS/I-Inheritance/Hybrid-Inheritance.cpp
  O-OOPS/I-Inheritance/README.md
Labels: enhancement, Feature-addition, next review needed, admin

#1309 Issue #1299 resolved: Find the missing and repeating number
  A-Array/MissingAndRepeatingNumber.cpp
  A-Array/README.md
Labels: enhancement, Feature-addition, admin

#1278 Coin change
  D-DynamicProgramming/CoinChange.cpp
  D-DynamicProgramming/README.md
Labels: enhancement, Feature-addition, problem-statement-addition, DataStructure, admin

#1301 Tree Recursion
  R-Recursion/Types of Recursion/README.md
  R-Recursion/Types of Recursion/TreeRecursion.cpp
Labels: enhancement, Feature-addition, next review needed, DataStructure, admin

#1300 Diagonal traversal of Binary Tree
  T-Tree/T-TreeTraversals/DiagonalTraversal.cpp
  T-Tree/T-TreeTraversals/README.md
Labels: enhancement, Feature-addition, problem-statement-addition, DataStructure, admin, changes-pending

#1333 Enhanced Readme
  T-Tree/T-TreeTraversals/MorrisTraversal.cpp
  T-Tree/T-TreeTraversals/README.md
Labels: enhancement, Feature-addition, next review needed, proposal, g1v

#1336 Official README.md
  README.md
Labels: enhancement, Feature-addition, admin

#1337 Fibonacci number
  R-Recursion/Fibonacci_Number.cpp
  R-Recursion/README.md
Labels: enhancement, Feature-addition, problem-statement-addition, admin

#1321 Queue using stacks
  Q-Queue/QueueUsingStacks.cpp
  Q-Queue/README.md
Labels: enhancement, Feature-addition, next review needed, DataStructure, admin

#1347 Enhanced Readme of Q-Queue folder
  Q-Queue/README.md
Labels: enhancement, Feature-addition, next review needed, admin

#1362 Issue #1318 resolved: Sort an array in wave form
  A-Array/README.md
  A-Array/SortingInWaveForm.cpp
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, DataStructure, admin

#1352 Power of 2
  R-Recursion/PowerOfTwo.cpp
  R-Recursion/README.md
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, admin

#1379 Indirect Recursion
  R-Recursion/Types of Recursion/IndirectRecursion.cpp
  R-Recursion/Types of Recursion/README.md
Labels: enhancement, Feature-addition, next review needed, algorithm, DataStructure, admin

#1353 Computing path matrix from powers of adjacency matrix
  G-Graphs/I-Implementation/PathMatrix.cpp
  G-Graphs/I-Implementation/Readme.md
  G-Graphs/README.md
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, DataStructure, admin

#1401 Word Wrap Problem
  P-Problem Statements & Solution/2-Level 2/README.md
  P-Problem Statements & Solution/2-Level 2/WordWrapProblem.cpp
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, admin

#1396 Added the code for printing the matrix in wave form
  A-Array/README.md
  A-Array/WavePrintOfMatrix.cpp
Labels: enhancement, Feature-addition, admin

#1395 Hash table and Linear probe Resolution method for Customer Details
  H-HashTable/HashCustomers.cpp
  H-HashTable/README.md
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, admin

#1348 Head Recursion
  R-Recursion/Types of Recursion/HeadRecursion.cpp
  R-Recursion/Types of Recursion/README.md
Labels: enhancement, Feature-addition, next review needed, admin

#1324 Doubly linked list
  L-LinkedList/D-DoublyLinkedList/DoublyLinkedListOperations.cpp
  L-LinkedList/D-DoublyLinkedList/README.md
Labels: enhancement, Feature-addition, problem-statement-addition, admin

#1406 Subsets Generation
  B-BitManipulation/README.md
  B-BitManipulation/SubsetsGeneration.cpp
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, admin

#1329 Tail Recursion
  R-Recursion/Types of Recursion/README.md
  R-Recursion/Types of Recursion/TailRecursion.cpp
Labels: enhancement, Feature-addition, problem-statement-addition, admin

#1413 Subsequence K Sum
  R-Recursion/README.md
  R-Recursion/SubsequenceKSUM.cpp
Labels: enhancement, Feature-addition, admin, changes-pending

#1411 Cycle Sort added
  S-SortingAlgorithms/CycleSort.cpp
  S-SortingAlgorithms/README.md
Labels: DataStructure, admin

#1212 Trie Data Structure Implementation
  T-Trie/README.md
  T-Trie/TrieImplementation.cpp
Labels: enhancement, Feature-addition, DataStructure, admin

#1439 Find Connected components in an undirected graph
  G-Graphs/ConnectedComponentUndirectedGraph.cpp
  G-Graphs/README.md
Labels: enhancement, Feature-addition, admin

#1327 Count Prefix Using Trie
  T-Trie/CountPrefix.cpp
  T-Trie/README.md
Labels: enhancement, Feature-addition, problem-statement-addition, admin

#1454 Reverse a Stack using Recursion
  S-Stack/README.md
  S-Stack/ReverseStack.cpp
Labels: enhancement, Feature-addition, problem-statement-addition, DataStructure, admin

#1408 Minimum Cost Of Ropes
  H-Heap/MinCostRopes.cpp
  H-Heap/README.md
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, admin

#1441 Ford Fulkerson Graph Algorithm
  G-GraphAlgorithms/FordFulkerson.cpp
  G-GraphAlgorithms/README.md
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, admin

#1486 Merge Sort-Divide And Conquer Algorithms
  D-DivideAndConquerAlgorithms/MergeSort.cpp
  D-DivideAndConquerAlgorithms/README.md
Labels: admin

#1483 Cousins binary tree
  T-Tree/B-BinaryTree/CousinsBinaryTree.cpp
  T-Tree/B-BinaryTree/README.md
Labels: enhancement, Approved, Feature-addition, Level1, GSSoC22, DataStructure, CGC

#1488 Count no. of Set Bits
  B-BitManipulation/README.md
Labels: enhancement, Feature-addition, next review needed, README, admin

#1478 Intersection of Sets
  S-Sets/IntersectionSets.cpp
  S-Sets/README.md
Labels: assigned, GSSoC22, DataStructure, admin

#1466 Conversion of expression by a expression tree traversal
  T-Tree/T-TreeTraversals/README.md
  T-Tree/T-TreeTraversals/expressionTreeTraversal.cpp
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, DataStructure, admin

#1462 Sort a Stack
  S-Stack/README.md
  S-Stack/SortStack.cpp
Labels: enhancement, Approved, Feature-addition, problem-statement-addition, Level2, GSSoC22, CGC

#1363 detect a cycle in a linked list
  L-LinkedList/S-SinglyLinkedList/DetectCycleInLinkedList.cpp
  L-LinkedList/S-SinglyLinkedList/README.md
Labels: good first issue, assigned, admin

#1129 Implementation of Shell Sort
  S-SortingAlgorithms/README.md
  S-SortingAlgorithms/ShellSort.cpp
Labels: enhancement, Feature-addition, next review needed, algorithm, admin

#270 Adding Vertical order Traversal of binary tree
  T-Tree/README.md
  T-Tree/T-TreeTraversals/verticalTraversal.cpp
Labels: enhancement, Feature-addition, problem-statement-addition, admin

#1504 Roman to Decimal
  S-Strings/README.md
  S-Strings/RomanDec.cpp
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, admin

#1460 Diamond Inheritance Problem Issue 1459
  O-OOPS/README.md
  O-OOPS/diamondInheritance.cpp
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, admin

#1433 Implementing two stacks using a single array
  S-Stack/README.md
  S-Stack/twoStackArray.cpp
Labels: assigned, DataStructure, admin, g2a

#1532 Created Right Side View of Binary Tree
  T-Tree/B-BinaryTree/README.md
  T-Tree/T-TreeTraversals/README.md
  T-Tree/T-TreeTraversals/RightSideViewOfBT.cpp
Labels: enhancement, question, Feature-addition, next review needed, admin, changes-pending

#1542 Found Kth Distinct Element from a string using Sets
  S-Sets/FindKthDistinctCharacterGivenString.cpp
  S-Sets/README.md
Labels: enhancement, Feature-addition, next review needed, admin

#1471 Interpolation Search
  S-SearchingAlgorithms/InterpolationSearch.cpp
  S-SearchingAlgorithms/README.md
Labels: enhancement, Feature-addition, algorithm, admin

#1358 Added a new Problem convert 24hr clock to 12hr clock with detailed explanation and code
  P-Problem Statements & Solution/1-Level 1/24hrTo12hrFormat.cpp
  P-Problem Statements & Solution/1-Level 1/README.md
Labels: enhancement, Feature-addition, admin

#1535 Pow (x,n): Divide-and-conquer # 1493
  D-DivideAndConquerAlgorithms/Pow.cpp
  D-DivideAndConquerAlgorithms/README.md
Labels: enhancement, Feature-addition, admin

#1437 Linear Recursion
  R-Recursion/Types of Recursion/LinearRecursion.cpp
  R-Recursion/Types of Recursion/README.md
Labels: assigned, admin

#1551 Boruvka's Algorithm
  G-Graphs/M-MinimumSpanningTree/Boruvka's_algorithm.cpp
  G-Graphs/M-MinimumSpanningTree/README.md
Labels: assigned, algorithm, DataStructure, admin

#1456 Direct Recursion
  R-Recursion/Types of Recursion/DirectRecursion.cpp
  R-Recursion/Types of Recursion/README.md
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, algorithm, admin
