Repository Lakhankumawat/LearnCPP, pull requests merged in 2022-04, with the labels that each got.

#1010 Climbing stairs
  D-DynamicProgramming/ClimbingStairs.cpp
  D-DynamicProgramming/README.md
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, g1s, README, changes-pending

#1043 Added Bucket Sort Algorithm
  S-SortingAlgorithms/BucketSort.cpp
  S-SortingAlgorithms/README.md
Labels: enhancement, Feature-addition, problem-statement-addition, admin

#1009 Factorial of large numbers
  M-MathematicalAlgorithms/Factorial of large numbers/FactorialLargeNumbers.cpp
  M-MathematicalAlgorithms/Factorial of large numbers/README.md
Labels: enhancement, Feature-addition, next review needed, algorithm, README, admin, changes-pending

#561 K_Query folder added with separate readme.
  T-Tree/F-FenwickTree/K_Query.cpp
  T-Tree/F-FenwickTree/Readme.md
Labels: enhancement, Feature-addition, next review needed, DataStructure, admin, changes-pending

#1091 set_union
  S-Sets/README.md
  S-Sets/SetUnion.cpp
Labels: enhancement, good first issue, Approved, Feature-addition, next review needed, GSSoC22, DataStructure, admin, g1j

#1065 Armstrong number
  M-MathematicalAlgorithms/ArmstrongNumber.cpp
  M-MathematicalAlgorithms/README.md
Labels: enhancement, Feature-addition, problem-statement-addition, admin

#1069 Symmetric Matrix
  A-Array/README.md
  A-Array/SymmetricMatrix.cpp
Labels: enhancement, good first issue, Feature-addition, next review needed, problem-statement-addition, GSSoC22, admin, changes-pending

#1094 Aggressive Cows Problem Statement
  P-Problem Statements & Solution/2-Level 2/AggressiveCows.cpp
  P-Problem Statements & Solution/2-Level 2/README.md
Labels: enhancement, Approved, Feature-addition, problem-statement-addition, GSSoC22, README, admin, changes-pending

#1027 CountingDivisibleSubstrings #489
  A-Array/CountingDivisibleSubstrings.cpp
  A-Array/README.md
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, GSSoC22, admin

#1078 Min cost climbing stairs
  D-DynamicProgramming/MinCostClimbingStairs.cpp
  D-DynamicProgramming/README.md
Labels: enhancement, Feature-addition, problem-statement-addition, admin

#1046 Stack ADT using Linked List
  S-Stack/README.md
  S-Stack/stackADTUsingLL.cpp
Labels: enhancement, Approved, Feature-addition, next review needed, problem-statement-addition, GSSoC22, DataStructure, admin

#1110 Unique paths
  D-DynamicProgramming/README.md
  D-DynamicProgramming/UniquePaths.cpp
Labels: enhancement, Approved, Feature-addition, GSSoC22, DataStructure, admin, changes-pending

#1100 Level order Traversal of a Generic Tree
  T-Tree/G-GenricTree/LevelOrderTraversalOfaGenricTree.cpp
  T-Tree/G-GenricTree/README.md
Labels: enhancement, Approved, Feature-addition, problem-statement-addition, GSSoC22, DataStructure, admin

#1099 Decimal to Binary Conversion
  S-Stack/DecimalToBinary.cpp
  S-Stack/README.md
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, GSSoC22, DataStructure, admin, changes-pending

#1125 Implementation Of Queue Using Array
  Q-Queue/QueueUsingArray.cpp
  Q-Queue/README.md
Labels: enhancement, Feature-addition, problem-statement-addition, GSSoC22, DataStructure, admin

#1115 Unique paths II
  D-DynamicProgramming/README.md
  D-DynamicProgramming/UniquePaths2.cpp
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, proposal, admin, changes-pending, CGC

#1097 Minor Changes to README.md
  README.md
Labels: next review needed, README, admin

#1101 Huffman coding and update readme accordingly
  G-GreedyAlgorithms/HuffmanCoding.cpp
  G-GreedyAlgorithms/README.md
Labels: enhancement, Feature-addition, problem-statement-addition, GSSoC22, algorithm, admin

#1072 Segmented Sieve
  M-MathematicalAlgorithms/S-SegmentedSieve/README.md
  M-MathematicalAlgorithms/S-SegmentedSieve/SegmentedSieve.cpp
Labels: enhancement, Feature-addition, problem-statement-addition, GSSoC22, admin

#1152 Calculating GCD and LCM by Recursion
  R-Recursion/README.md
  R-Recursion/Recursive_GCD_LCM.cpp
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, GSSoC22, admin, changes-pending

#1150 Lambda function in Cpp
  Miscellaneous/Lambda_Functions.cpp
  Miscellaneous/README.md
Labels: enhancement, good first issue, Feature-addition, next review needed, problem-statement-addition, GSSoC22, admin

#1168 StringComparison
  S-Strings/README.md
  S-Strings/StringComparison.cpp
Labels: enhancement, good first issue, next review needed, problem-statement-addition, GSSoC22, DataStructure, README, admin, changes-pending

#657 Number of leaf nodes in binary tree
  T-Tree/B-BinaryTree/No_of_leaf_nodes.cpp
  T-Tree/B-BinaryTree/Readme.md
Labels: enhancement, Feature-addition, problem-statement-addition, admin

#1122 Juggler sequence
  M-MathematicalAlgorithms/JugglerSequence/JugglerSequence.cpp
  M-MathematicalAlgorithms/JugglerSequence/README.md
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, GSSoC22, DataStructure, admin, changes-pending

#1086 Taylors series By Horner's rule
  R-Recursion/README.md
  R-Recursion/TaylorsSerieHornersRule.cpp
Labels: enhancement, Feature-addition, problem-statement-addition, admin, changes-pending

#1079 Added the Code for Array Operations Problem. Performed various operations such as Traversal ,Insertion, Deletion & Searching in the Array
  A-Array/README.md
  A-Array/arrayOperations.cpp
Labels: enhancement, Feature-addition, README, admin

#465 #395: Created a C++ file and updated readme for Shortest Common Super-sequence
  D-DynamicProgramming/README.md
  D-DynamicProgramming/ShortestCommonSuperSequence.cpp
Labels: enhancement, Feature-addition, problem-statement-addition, admin

#1170 Create and display adjacency matrix of a graph
  G-Graphs/I-Implementation/AdjacencyMatrix.cpp
  G-Graphs/I-Implementation/Readme.md
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, GSSoC22, admin

#540 OOPS - Operator Overloading [Updated README and removed all cpp files but one]
  O-OOPS/OperatorOverloadingBinary.cpp
  O-OOPS/README.md
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, g2m

#1191 Iterative Preorder and Postorder Traversal of Generic Tree
  T-Tree/G-GenricTree/IterativePreorderandPostorder.cpp
  T-Tree/G-GenricTree/README.md
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, GSSoC22, DataStructure, admin, changes-pending

#1184 Implementation Of Queue Using Linked List
  Q-Queue/QueueUsingLinkedList.cpp
  Q-Queue/README.md
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, GSSoC22, admin

#1169 Exception Handling in Cpp
  Miscellaneous/Exception_Handling.cpp
  Miscellaneous/README.md
Labels: enhancement, Feature-addition, next review needed, GSSoC22, admin

#1196 Update README.md
  L-LinkedList/C-CircularLinkedList/README.md
  L-LinkedList/README.md
Labels: enhancement, Feature-addition, next review needed, assigned, DataStructure, proposal, README, admin, changes-pending

#1207 Circular queue using array
  Q-Queue/CircularQueueUsingArray.cpp
  Q-Queue/README.md
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, admin

#1139 Minimum Falling Path Sum
  D-DynamicProgramming/MinimumFallingPathSum.cpp
  D-DynamicProgramming/README.md
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, admin, changes-pending

#331 Rod Cutting Problem using Dynamic Programming
  D-DynamicProgramming/README.md
  D-DynamicProgramming/RodCutting.cpp
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, admin, changes-pending

#791 Nge
  S-Stack/NextGreaterElement/README.md
  S-Stack/NextGreaterElement/nge.cpp
Labels: enhancement, Feature-addition, problem-statement-addition, admin, changes-pending

#1216 Reversing of array
  A-Array/README.md
  A-Array/Reversingofarray.cpp
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, DataStructure, admin, changes-pending, g1j

#1182 Intro to inheritance
  O-OOPS/I-Inheritance/README.md
  O-OOPS/I-Inheritance/Single-Inheritance.cpp
Labels: enhancement, Feature-addition, next review needed, admin, changes-pending

#1230 Searching in a linked list
  L-LinkedList/S-SinglyLinkedList/README.md
  L-LinkedList/S-SinglyLinkedList/SearchingInALinkedList.cpp
Labels: enhancement, Feature-addition, next review needed, admin

#1231 Templates in C++
  T-Template/ClassTemplate.cpp
  T-Template/FunctionTemplate.cpp
  T-Template/README.md
Labels: enhancement, Feature-addition, next review needed, admin

#1219 Binding concept in C++
  O-OOPS/B-Binding/EarlyBinding.cpp
  O-OOPS/B-Binding/LateBinding.cpp
  O-OOPS/B-Binding/README.md
Labels: enhancement, Feature-addition, next review needed, admin, changes-pending

#1244 Access modifiers in inheritance
  O-OOPS/I-Inheritance/AccessModifiersInInheritance.cpp
  O-OOPS/I-Inheritance/README.md
Labels: enhancement, Feature-addition, next review needed, DataStructure, admin

#1250 The Knight’s tour problem
  B-Backtracking/README.md
  B-Backtracking/TheKnight’stourproblem.cpp
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, DataStructure, admin

#1248 Delete and Add edge in directed graph of adjacency matrix
  G-Graphs/I-Implementation/DelAddEdgeAdjacencyMatrix.cpp
  G-Graphs/I-Implementation/Readme.md
Labels: enhancement, Approved, Feature-addition, problem-statement-addition, Level1, GSSoC22, DataStructure, CGC

#1257 KMP Algorithm
  S-StringAlgorithms/KMP/README.md
  S-StringAlgorithms/KMP/kmp.cpp
Labels: enhancement, Feature-addition, next review needed, algorithm, DataStructure, admin

#1260 Construct BST From Preorder
  T-Tree/B-BinarySearchTree/ConstructBSTFromPreoderTraversal.cpp
  T-Tree/B-BinarySearchTree/readme.md
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, admin

#1258 Multilevel inheritance
  O-OOPS/I-Inheritance/Multilevel-Inheritance.cpp
  O-OOPS/I-Inheritance/README.md
Labels: enhancement, Feature-addition, next review needed, admin

#1227 Knapsack with duplicate items
  D-DynamicProgramming/KnapsackwithDuplicateItems.cpp
  D-DynamicProgramming/README.md
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, DataStructure, admin

#1275 Minimum number of deletions and insertions required to transform one string into another
  D-DynamicProgramming/MinimumInsertionDeletion.cpp
  D-DynamicProgramming/README.md
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, DataStructure, admin

#1179 Longest word in a Sentence (String based question)
  S-Strings/LongestWordInSentence.cpp
  S-Strings/README.md
Labels: enhancement, Feature-addition, next review needed, problem-statement-addition, admin
